### ISSUE TITLE
dependencies errors and wandb

### ISSUE THREAD

**Issue by DH-O** [nsidn98/InforMARL#1]
Sorry, I'm not familiar with this kind of code, so under questions can be ridiculous.

1. The torch version in the requirement.txt and dependencies of MAPE are different from 1.8.0 and 1.11.0. So should I install 1.11.0?

2. When I pip install libraries, torch-* things are not installed well.

3.  I'm not familiar with wandb. Do you know if the next error is usual?
```wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)```
Should I get your permission...? Or do you mean I should turn off the wandb.

Thanks for your help.

**Comment by nsidn98** [comment]
Hi @DH-O no worries at all! 

1. I think we trained/tested our models on torch==1.11.0. Are you getting an error when you try to install MAPE? I have updated the requirement.txt file.
2. Could you show the errors you are getting while installing the torch related libraries?
3. You will need to change the `--user_name` flag to your wandb username. Refer this: https://docs.wandb.ai/guides/app/settings-page/user-settings. You will need to get an API key from wandb as well (it is free to use)

**Comment by reidsouchultralabs** [comment]
> Hi @DH-O no worries at all!
> 
> 1. I think we trained/tested our models on torch==1.11.0. Are you getting an error when you try to install MAPE? I have updated the requirement.txt file.
> 2. Could you show the errors you are getting while installing the torch related libraries?
> 3. You will need to change the `--user_name` flag to your wandb username. Refer this: https://docs.wandb.ai/guides/app/settings-page/user-settings. You will need to get an API key from wandb as well (it is free to use)

I am also trying to install the repository. I have tried with python 3.7, 3.8, and 3.10 and I get a `subprocess-exited-with-error` when installing requirements. This happens when the install gets to `torch-cluster`. Could you please let me know what python version was originally used for this? Maybe that will help.

**Comment by DH-O** [comment]
1, 2.
I solved the issues by installing torch-* things through conda install as below
`conda install -c esri torch-cluster` 
[(https://anaconda.org/Esri/torch-cluster)]

The problem was that torch==1.11.0 is not compatible with torch-cluster==1.5.9
In my case, requirement.txt should be like this

```
absl-py
gym==0.10.5
numpy==1.19.4
pyglet==1.5.26
protobuff==3.20.0
PyOpenGL==3.1.5
PyQt5==5.9.2
requests==2.22.0
tensorboard==2.4.0
tensorboard-plugin-wit==1.7.0
tensorboardX==2.1
torch==1.8.1
torch-cluster==1.5.9
torch-geometric==2.0.4
torch-scatter==2.0.7
torch-sparse==0.6.10
torch-spline-conv==1.2.1
torchvision==0.9.1
tqdm==4.44.1
typing==3.6.4
typing-extensions==3.7.4.3
wandb==0.10.31
```

after that, there seem to be no library issues.

3. Thank you after changing the user_name flag, it works well.

**Comment by nsidn98** [comment]
@DH-O glad that everything works well now. I will update the requirements.txt. Thanks a lot!

**Comment by nsidn98** [comment]
@reidsouchultralabs we tested using python 3.8 and 3.10.
Could you try installing all torch related stuff using this:
```
TORCH="1.8.0"
CUDA="cu102"
pip install --no-index torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html --user
pip install --no-index torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html --user
pip install torch-geometric --user
```

Also, could you show the error traceback so that I can help debugging it?

**Comment by nsidn98** [comment]
@reidsouchultralabs were you able to install it? Do you need help in debugging? Can I close this issue?

**Comment by reidsouchultralabs** [comment]
> @reidsouchultralabs were you able to install it? Do you need help in debugging? Can I close this issue?

Hey. I cannot get it installed. I tried with both Python 3.8 and 3.10. With conda, I get dependency errors with the versions in requirement.txt... Do you have any suggestions?

**Comment by nsidn98** [comment]
Can you show the dependency errors you are getting?

**Comment by reidsouchultralabs** [comment]
> Can you show the dependency errors you are getting?

With python 3.10, using `pip install -r requirement.txt` :
`Collecting numpy==1.19.4
  Using cached numpy-1.19.4.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [288 lines of output]
      setup.py:67: RuntimeWarning: NumPy 1.19.4 may not yet support Python 3.10.`

Removing numpy and installing separately, I get: `ERROR: Could not find a version that satisfies the requirement protobuff==3.20.0 (from versions: none)
ERROR: No matching distribution found for protobuff==3.20.0`

similarly... `ERROR: Could not find a version that satisfies the requirement torch==1.8.1 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0)
ERROR: No matching distribution found for torch==1.8.1`

**Comment by nsidn98** [comment]
Did you try installing one library at a time instead of `pip install -r requirements.txt`? Can you give more information about your OS and if you are using conda or not?

**Comment by reidsouchultralabs** [comment]
> Did you try installing one library at a time instead of `pip install -r requirements.txt`? Can you give more information about your OS and if you are using conda or not?

I am using linux through WSL. When installing with pip individually, I get the same errors. I will try one by one with conda and get back to you.

**Comment by reidsouchultralabs** [comment]
> > Did you try installing one library at a time instead of `pip install -r requirements.txt`? Can you give more information about your OS and if you are using conda or not?
> 
> I am using linux through WSL. When installing with pip individually, I get the same errors. I will try one by one with conda and get back to you.

@nsidn98 I was able to get everything installed. I had to use python 3.8 and install each package individually with pip.

**Comment by nsidn98** [comment]
@reidsouchultralabs Great! I'll close the issue now. Reopen if you need help with it!
