### ISSUE TITLE
Formation, Coverage and Line

### ISSUE THREAD

**Issue by ljymrl** [nsidn98/InforMARL#13]
Hello, thanks again for your open source project, I have another question: how can I test the performance of the algorithm in the 3 scenarios of Formation, Coverage and Line?

**Comment by nsidn98** [comment]
Hi @ljymrl, apologies for the late reply! We forgot to push the code for those environments. We will push it to the repo soon.

**Comment by ljymrl** [comment]
> 嗨，很抱歉回复晚了！我们忘了为这些环境推送代码。我们将很快将其推送到回购。

Thank you very much!

**Comment by nsidn98** [comment]
Reopening this issue so that I can remember to add these to the repo.

**Comment by ljymrl** [comment]
> 重新打开此问题，以便我记得将这些添加到存储库中。
I have found these environment programs under this path baselines/mpnn/mpe/mape/multiagent/scenarios, thank you!
