### ISSUE TITLE
Understanding of graph neural networks?

### ISSUE THREAD

**Issue by Yu-zx** [nsidn98/InforMARL#17]
Yǒu guānyú onpolicy zhèlǐ, wǒ xiǎng wèn wèn zhèlǐ shì zěnme yùnxíng tǐxiàn gnn, mùqián lái shuō zhèlǐ wǒ zhǐshì kàn dàole rnn-mappo,mappo zhè liǎng gè suànfǎ zài train.Py, nàme shìfǒu zhīchí gnn-mappo ne, zhège jùtǐ de guānlián shì zěnme yàng de ne? Dāngrán wǒ zhīdào jiàn mó de shíhòu shì tú dǎoháng de fāngshì, zhǐshì yùnxíng zhège jiǎoběn hòu, jùtǐ dōu shì nǎxiē wénjiàn fāshēngle liándòng ne? Python -u onpolicy/scripts/train_mpe.Py --use_valuenorm --use_popart\--project_name"informarl" \--env_name"GraphMPE"\--algorithm_name"rmappo" \--seed th\--experiment_name"informarl" \--scenario_name"navigation_graph" \--num_agents 3\--collision_rew 5\--n_training_threads 1 --n_rollout_threads 128\--num_mini_batch 1\--episode_length 25\--num_env_steps 2000000\--ppo_epoch 10 --use_ReLU --gain 0.01 --Lr 7e-4 --critic_lr 7e-4\--user_name"marl" \--use_cent_obs"False" \--graph_feat_type"relative" \--auto_mini_batch_size --target_mini_batch_size 128
Show more
715 / 5,000
Regarding onpolicy, I would like to ask how to run gnn here. At present, I only see the two algorithms of rnn-mappo and mappo in train.py. So does it support gnn-mappo? What is the specific connection? Of course, I know that the modeling is done by graph navigation, but after running this script, which specific files are linked?

python -u onpolicy/scripts/train_mpe.py --use_valuenorm --use_popart \--project_name "informarl" \--env_name "GraphMPE" \--algorithm_name "rmappo" \--seed θ\--experiment_name "informarl" \--scenario_name "navigation_graph" \--num_agents 3 \--collision_rew 5 \--n_training_threads 1 --n_rollout_threads 128 \--num_mini_batch 1 \--episode_length 25 \--num_env_steps 2000000 \--ppo_epoch 10 --use_ReLU --gain 0.01 --lr 7e-4 --critic_lr 7e-4 \--user_name "marl" \--use_cent_obs "False" \--graph_feat_type "relative" \--auto_mini_batch_size --target_mini_batch_size 128

**Comment by nsidn98** [comment]
When you use the `--env_name "GraphMPE"` in conjunction with `--algorithm_name "rmappo"`, the code automatically uses the GNN version of MAPPO (our method InforMARL). You can refer to this [line](https://github.com/nsidn98/InforMARL/blob/30416b53f248cb3c6530a873d724dbeaaf7497cd/onpolicy/scripts/train_mpe.py#L280) where we import separate Runners based on whether we want to use the graph version or not.

If you set `--env_name "MPE"` then it will use the non-graph algorithm.

I hope this answers your question.

**Comment by Yu-zx** [comment]
The current algorithm can be understood as follows: First, use the graph neural network to process the graph structure observation and processing in the multi-agent environment, and then use the rmappo algorithm. This constitutes the algorithm process. Our algorithm file contains gnn processing graph structure observation information, and then uses the rnn-mappo algorithm. Is this understanding correct?

**Comment by nsidn98** [comment]
Yes, that is right. Use the GNN for processing the graph inputs with a variable number of nodes. And then use RMAPPO with the GNN-processed output.

**Comment by Yu-zx** [comment]
准确来说，运行这样的一个程序，比如当运行了这个程序的话，当运行调用的程序包括了哪些关联文件呢？可以用一个来举例子说明嘛
![image](https://github.com/nsidn98/InforMARL/assets/83055172/cb1c42df-465b-4385-bce9-f5ea25d7afb2)

**Comment by nsidn98** [comment]
> To be precise, when running such a program, for example, when running this program, what associated files are included in the called program? Can you give me an example? (translated your previous reply)

So here, all files with the `graph` prefix are used in conjunction with the graph modules. This will add the GNN architecture introduced in InforMARL to the RMAPPO and also use the graph_navigation scenario. These files are obtained by modifying the vanilla mappo files (non-graph prefix ones).

**Comment by nsidn98** [comment]
@Yu-zx does this answer your question? Could you close the issue if it is resolved? Thanks!

**Comment by Yu-zx** [comment]
Thanks
