### ISSUE TITLE
Problems encountered when running with Windows?

### ISSUE THREAD

**Issue by Yu-zx** [nsidn98/InforMARL#18]
After configuring the environment as required, I encountered this problem when running the scene multiagent/custom_scenarios/navigation_graph.py on Windows, but it can run normally on Linux. I would like to ask specifically about this, is it currently not supported on Windows?

Traceback (most recent call last):
  File "D:\code\DRL\InforMARL\multiagent\custom_scenarios\navigation_graph.py", line 566, in <module>
    policies = [InteractivePolicy(env, i) for i in range(env.n)]
  File "D:\code\DRL\InforMARL\multiagent\custom_scenarios\navigation_graph.py", line 566, in <listcomp>
    policies = [InteractivePolicy(env, i) for i in range(env.n)]
  File "D:\code\DRL\InforMARL\multiagent\policy.py", line 26, in __init__
    env.viewers[agent_index].window.on_key_press = self.key_press
AttributeError: 'NoneType' object has no attribute 'window'

**Comment by nsidn98** [comment]
I have not tested it on Windows. But, I believe this error is probably through gym/pyqt. Can you show me the versions of the following libraries? I have listed the library versions with which it should ideally work
```
gym==0.10.5
numpy==1.19.4
pyglet==1.5.26
protobuff==3.20.0
PyOpenGL==3.1.5
PyQt5==5.9.2
```

**Comment by Yu-zx** [comment]
我尝试了这样的版本之后，运行出来是空白的页面 
<img width="534" alt="PixPin_2024-06-18_09-13-00" src="https://github.com/nsidn98/InforMARL/assets/83055172/af01ac01-783b-411e-8a58-d45ae635f013">

**Comment by nsidn98** [comment]
Ideally, this should be a window with the rendering of the environment. I am not sure what is wrong here.

**Comment by nsidn98** [comment]
@Yu-zx are you still facing this issue?

**Comment by Yu-zx** [comment]
Still not solved, I don't know why it still shows such a blank?

**Comment by nsidn98** [comment]
I am really sorry about this issue. Did you try installing these versions for the libraries mentioned [here](https://github.com/nsidn98/InforMARL/issues/18#issuecomment-2173750543)?

**Comment by Yu-zx** [comment]
I have already installed these versions, unfortunately I have no idea how to solve this problem for you?

**Comment by nsidn98** [comment]
I am sorry, I do not have a windows machine to reproduce this error. But I am guessing you are able to get it working on Linux right?

**Comment by Yu-zx** [comment]
Yes, it can be run on Linux.

**Comment by nsidn98** [comment]
Gotcha! Closing the issue.
