### ISSUE TITLE
Which one should be set to true, use_popart or use_valuenorm?

### ISSUE THREAD

**Issue by DH-O** [nsidn98/InforMARL#2]
According to README.md, `use_popart` and `use_valuenorm` are both True, I think.

However, there is an assertion that both of them should not be True, in `graph_mappo.py`, line 52

**Comment by nsidn98** [comment]
Hi @DH-O, `use_popart` and `use_valuenorm` are not True at the same time. If you look at [this](https://github.com/nsidn98/InforMARL/blob/6e758c8bc97d1c9aa12920288bfbb584ef58e7e3/onpolicy/config.py#L249) line, `use_popart` has `store_true` and `use_valuenorm` has `store_false`. So if you are using both flags in the script, then `use_popart` is True and `use_valuenorm` is False.
