### ISSUE TITLE
How to speed up training

### ISSUE THREAD

**Issue by finleygou** [nsidn98/InforMARL#24]
I found it very slow when training graph_navigation scenario, it took 4 days to train a model of 5 agents with RTX3090. I removed the transformer in gnn and it still takes 2 days. Do you have any idea on how to speed up training with a little code modification?

**Comment by nsidn98** [comment]
Yes, a labmate of mine has achieved significant speedups by optimizing the training process. We will push the update soon in the repo and let you know.

@Jaroan could you please submit a PR for the speed-up you achieved with your modifications?

**Comment by Yu-zx** [comment]
Specifically, when is this push?

**Comment by finleygou** [comment]
> Yes, a labmate of mine has achieved significant speedups by optimizing the training process. We will push the update soon in the repo and let you know.
> 
> @Jaroan could you please submit a PR for the speed-up you achieved with your modifications?

Thanks a lot, looking forward to your push! It would be nice of you to update the code soon~

**Comment by nsidn98** [comment]
@finleygou we have the speedup pushed to the repo. You can refer to the latest [PR](https://github.com/nsidn98/InforMARL/commit/f3b101509ff682c8be5dc0795c65fba2ae9da977) for more information.

**Comment by finleygou** [comment]
> @finleygou we have the speedup pushed to the repo. You can refer to the latest [PR](https://github.com/nsidn98/InforMARL/commit/f3b101509ff682c8be5dc0795c65fba2ae9da977) for more information.

Appreciate it!
