### ISSUE TITLE
shared vs separate

### ISSUE THREAD

**Issue by mhmd97z** [nsidn98/InforMARL#30]
Hi, I noticed that the agents are designed to share the same parameters in your algorithm. This way all agents' experiences can be reused to train the same model parameters. Also, [the replay buffer samples](https://github.com/nsidn98/InforMARL/blob/ab69869fded4d856df3897386b8f922a8713681f/onpolicy/utils/graph_buffer.py#L447) are a sub-graph (and the corresponding agents) of the batch gaph rather than the entire graph. Is my understanding correct?

**Comment by nsidn98** [comment]
Yes, you can pull the relevant sub-graphs for each agent from the buffer.

**Comment by mhmd97z** [comment]
Thanks for your response. 
So we'd need the ID of the agent's neighbors and their local observations, right? 
What are the corresponding variables' names in the replay buffer of your implementation?
