### ISSUE TITLE
Hi, could you please tell how to use UniMP in your InforMARL? I can neither find it in your paper nor in your code. Thx.

### ISSUE THREAD

**Issue by TianyQi** [nsidn98/InforMARL#5]
Hi, could you please tell how to use UniMP in your InforMARL? I can neither find it in your paper nor in your code. Thx.

**Comment by nsidn98** [comment]
Hi @TianyQi, we use the graph transformer operator defined in UniMP [here](https://github.com/nsidn98/InforMARL/blob/304e905d05b34d9bf06046eb7e03904b97a14231/onpolicy/algorithms/utils/gnn.py#L223). You can find the PyTorch Geometric documentation for that layer [here](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.TransformerConv.html).

**Comment by TianyQi** [comment]
Thanks a lot for your reply~

**Comment by nsidn98** [comment]
Closing this comment because the issue seems to be resolved. Reopen if required.
