### ISSUE TITLE
Local vs Global Information

### ISSUE THREAD

**Issue by Michael-Elrod-dev** [nsidn98/InforMARL#8]
Hello again, 
I wanted to ask about the node observations within this project. I see that although the agents are only meant to have access to the information within their visual radius (and their neighboring agents), they do have access to the location of their goal.

My question is, do they obtain the position of their goals through local observations or are they given this piece of global information from the beginning of each episode?

I am specifically referring to the `_get_entity_feat_relative` function in `navigation_graph.py` where the agents calculate the distance to their goal positions here:
https://github.com/nsidn98/InforMARL/blob/304e905d05b34d9bf06046eb7e03904b97a14231/multiagent/custom_scenarios/navigation_graph.py#L508

**Comment by nsidn98** [comment]
The agents know the global positions of their goals and also their location. This was motivated by the drone delivery systems where the drones know their target locations. I hope this answers your question!
